# - platform: workday
#   country: US
#   state: IN
#   workdays: [mon, tue, wed, thu, fri]
# - platform: iss
- platform: template
  sensors:
    # Laundry room motion
    laundry_motion:
      entity_id: sensor.laundry_motion_level
      friendly_name: "Laundry Room Motion"
      value_template: >-
        { states.sensor.laundry_motion_level.state|int = 8  }
    # Anyone Home
    home_occupied:
      entity_id:
        - device_tracker.kamspixel
        - device_tracker.nickspixel
        - device_tracker.kameries_pixel
        - device_tracker.nickspixel_wifi
        - device_tracker.billies_phone
      value_template: >-
        {{ is_state('device_tracker.kamspixel', 'home')
           or is_state('device_tracker.nickspixel', 'home')
           or is_state('device_tracker.kameries_pixel', 'home')
           or is_state('device_tracker.nickspixel_wifi', 'home')
           or is_state('device_tracker.billies_phone', 'home') }}
# PING SENSORS
- platform: ping
  host: 172.18.19.5
  name: Rec Room AP
  count: 3
  scan_interval: 180
- platform: ping
  host: 172.18.19.6
  name: Living Room AP
  count: 3
  scan_interval: 180
# - platform: ping
#   host: grafana
#   name: Grafana Accessible
#   count: 2
#   scan_interval: 30
# DOOR SENSORS
- platform: "mqtt"
  state_topic: "zigbee2mqtt/front_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Front Door"
  icon: "mdi:door"
  value_template: "{{ value_json.contact }}"
  payload_off: true
  payload_on: false
  json_attributes:
    - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Rec Room Door"
  icon: "mdi:door"
  value_template: "{{ value_json.contact }}"
  payload_off: true
  payload_on: false
  json_attributes:
    - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/back_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Back Door"
  icon: "mdi:door"
  value_template: "{{ value_json.contact }}"
  payload_off: true
  payload_on: false
  json_attributes:
    - "linkquality"
## DUMMY for Garage Floorplan
- platform: random
  name: "Fake Workshop Door"
- platform: random
  name: "Fake Storage Door"