# - platform: workday
#   country: US
#   state: IN
#   workdays: [mon, tue, wed, thu, fri]
# - platform: iss
- platform: template
  sensors:
    # Laundry room motion
    laundry_motion:
      entity_id: sensor.laundry_motion_level
      friendly_name: "Laundry Room Motion"
      value_template: >-
        { states.sensor.laundry_motion_level.state|int = 8  }
    # Anyone Home
    home_occupied:
      entity_id:
        - device_tracker.kamspixel
        - device_tracker.nickspixel
        - device_tracker.billies_phone
      value_template: >-
        {{ is_state('device_tracker.kamspixel', 'home')
           or is_state('device_tracker.nickspixel', 'home')
           or is_state('device_tracker.billies_phone', 'home') }}
# DUMMY SENSOR FOR ha_floorplan
- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
# PING SENSORS
# - platform: ping
#   host: grafana
#   name: Grafana Accessible
#   count: 2
#   scan_interval: 30
# DOOR SENSORS
- platform: "mqtt"
  state_topic: "zigbee2mqtt/front_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Front Door"
  icon: "mdi:door"
  value_template: {{ value_json.contact }}
  payload_on: true
  payload_off: false
  json_attributes:
    - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Rec Room Door"
  icon: "mdi:door"
  value_template: {{ value_json.contact }}
  payload_on: true
  payload_off: false
  json_attributes:
    - "linkquality"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/back_door"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "Back Door"
  icon: "mdi:door"
  value_template: {{ value_json.contact }}
  payload_on: true
  payload_off: false
  json_attributes:
    - "linkquality"