   ##-----------##
  ###  SENSORS  ###
   ##-----------##

##########################
##   CUSTOM SENSORS     ##
##########################
# - platform: template
#   sensors:
#     kamerie_phone_percent:
#       friendly_name: "Kamerie's Phone Percentage"
#       unit_of_measurement: "%"
#       value_template: "{{ states.device_tracker.ot_kamphone.attributes.battery }}"
#     nick_phone_percent:
#       friendly_name: "Nick's Phone Percentage"
#       unit_of_measurement: "%"
#       value_template: "{{ states.device_tracker.ot_nickspixel.attributes.battery }}"

##########################
##      CMD SENSORS     ##
##########################
# - platform: command_line
#   name: "Download Grafana Images"
#   command: 'sh /config/scripts/grafana.sh'
#   polling_interval: 180
##########################
##   SIMPLE SENSORS     ##
##########################
- platform: season
  type: astronomical
- platform: moon

##########################
## DARK SKY SENSORS     ##
##########################
- platform: darksky
  api_key: 6618f0765eba51bcc5581b98c5e48e91
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
  monitored_conditions:
    - icon
    - summary
    - nearest_storm_distance
    - nearest_storm_bearing
    - humidity
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - wind_speed
    - wind_bearing
    - precip_type
    - precip_probability
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - uv_index
    - daily_summary
    - pressure
    - visibility
  update_interval:
    minutes: 10
##########################
## POLLEN SENSOR        ##
##########################
# - platform: pollen
#   zip_code: !secret home_zip
#   monitored_conditions:
#     - allergy_average_forecasted
#     - allergy_average_historical
#     - allergy_index_today
#     - allergy_index_tomorrow
#     - allergy_index_yesterday
#     - disease_average_forecasted
##########################
## AIR QUALITY SENSOR   ##
##########################
# - platform: waqi
#   token: cb5d3bc14aac4984dbabf76e7cebdc6f90685469
#   locations:
#   - indpls
##########################
##     MEAN SENSORS     ##
##########################
- platform: min_max
  type: mean
  name: Average Indoor Temperature Zone A
  entity_ids:
  - sensor.averys_room_temperature
  - sensor.guest_room_temperature
  - sensor.guest_bathroom_temperature
  - sensor.living_room_thermostat_temperature
  - sensor.master_bedroom_temperature
- platform: min_max
  type: mean
  name: Average Indoor Temperature Zone B
  entity_ids:
  - sensor.network_rack_temperature
  - sensor.kams_desk_temperature
  - sensor.recroom_temperature_sink
  - sensor.laundry_room_temperature
- platform: min_max
  type: mean
  name: Average Indoor Temperature
  entity_ids:
  - sensor.average_indoor_temperature_zone_a
  - sensor.average_indoor_temperature_zone_b
##########################
##     MQTT SENSORS     ##
##########################
## NETWORK RACK HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "network_rack_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## NETWORK RACK TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "network_rack_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## LAUNDRY ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "laundry_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## LAUNDRY ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "laundry_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## KAMERIES DESK HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "kams_desk_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## KAMERIES DESK TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "kams_desk_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST BATHROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "guest_bathroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST BATHROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_bathroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "guest_room_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## AVERYS ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "averys_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## AVERYS ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "averys_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## BEDROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "master_bedroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## BEDROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "master_bedroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## RECROOM_SOUTH HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_southwall"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "recroom_humidity_southwall"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## RECROOM_SOUTH TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_southwall"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "recroom_temperature_southwall"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## KITCHEN HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "kitchen_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## KITCHEN TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "kitchen_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"