##########################
##     MQTT SENSORS     ##
##########################
## NETWORK RACK HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "network_rack_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## NETWORK RACK TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "network_rack_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## LAUNDRY ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "laundry_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## LAUNDRY ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "laundry_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## KAMERIES DESK HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "kams_desk_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## KAMERIES DESK TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "kams_desk_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST BATHROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "guest_bathroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST BATHROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_bathroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "guest_room_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## GUEST ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## AVERYS ROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "averys_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## AVERYS ROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "averys_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
## BEDROOM HUMIDITY
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "master_bedroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
## BEDROOM TEMPERATURE
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "master_bedroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"