- platform: mjpeg
  name: Exterior 1
  mjpeg_url: !secret blueiris_url_ext01
- platform: mjpeg
  name: Exterior 2
  mjpeg_url: !secret blueiris_url_ext02
- platform: mjpeg
  name: Exterior 3
  mjpeg_url: !secret blueiris_url_ext03