- platform: switch
  name: RecRoom Ceiling
  entity_id: switch.recroom_ceiling

- platform: switch
  name: RecRoom Corner
  entity_id: switch.recroom_corner

- platform: group
  name: All Rec Room Lights
  entities:
      - light.recroom_ceiling
      - light.recroom_corner
      - light.recroom_table
      - light.recroom_wall