- platform: command_line
  name: Remove excess latest jpgs
  command: "rm -v /config/tensorflow/images/*_latest.jpg ||:"
  # The '||:' makes it so this command will never "fail" and always be OK
  scan_interval: 3600