# So.. device trackers. They are nice and all but when you have more than one combined
# (like by using gpslogger to send updates to 'nickspixel' and putting a MAC address for
# it so that Unifi can update the same device_tracker), you will end up with conflicts that
# spam switch from home to not_home until both agree.
# Since there isn't a way built-in to home assistant to assign devices to people, that what
# these sensors do. They also are putting 'Home' and 'Away' because they are nicer to read than
# the lower case versions (and Away is nicer than 'not_home' lol).
- platform: template
  sensors:
    location_kam:
      friendly_name: "Kamerie's Location"
      value_template: >
        {% if is_state('device_tracker.kamspixel', 'home') or
              is_state('device_tracker.kameries_pixel', 'home') %}
          Home
        {% elif is_state('device_tracker.kamspixel', 'not_home') %}
          Away
        {% else %}
          {{ states('device_tracker.kamspixel') }}
        {% endif %}
      entity_picture_template: /local/people/kamerie.jpg
    location_nick:
      friendly_name: "Nick's Location"
      value_template: >
        {% if is_state('device_tracker.nickspixel', 'home') or
              is_state('device_tracker.nickspixel_wifi', 'home') %}
          Home
        {% elif is_state('device_tracker.nickspixel', 'not_home') %}
          Away
        {% else %}
          {{ states('device_tracker.nickspixel') }}
        {% endif %}
      entity_picture_template: /local/people/nick.png
    location_billie:
      friendly_name: "Billie's Location"
      value_template: >
        {% if is_state('device_tracker.billies_phone', 'home') %}
          Home
        {% elif is_state('device_tracker.billies_phone', 'not_home') %}
          Away
        {% else %}
          {{ states('device_tracker.billies_phone') }}
        {% endif %}
      entity_picture_template: /local/people/billie.png
