- platform: pi_hole
  host: !secret pihole_host
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - unique_clients
    - queries_cached
    - queries_forwarded