## Binary Sensors based on the Router Device Tracker
## Tells me if the router sees the camera connected or not!
- platform: template
  sensors:
    int_dome_01:
      device_class: door
      entity_id: device_tracker.int_dome_01
      friendly_name: Int Dome 01 Connected
      value_template: "{{ is_state('device_tracker.int_dome_01', 'home') }}"
    ext_cam_01:
      device_class: door
      entity_id: device_tracker.ext_cam_01
      friendly_name: Ext Cam 01 Connected
      value_template: "{{ is_state('device_tracker.ext_cam_01', 'home') }}"
    ext_cam_02:
      device_class: door
      entity_id: device_tracker.ext_cam_02
      friendly_name: Ext Cam 02 Connected
      value_template: "{{ is_state('device_tracker.ext_cam_02', 'home') }}"
    ext_cam_03:
      device_class: door
      entity_id: device_tracker.ext_cam_03
      friendly_name: Ext Cam 03 Connected
      value_template: "{{ is_state('device_tracker.ext_cam_03', 'home') }}"
    ext_dome_01:
      device_class: door
      entity_id: device_tracker.ext_dome_01
      friendly_name: Ext Dome 01 Connected
      value_template: "{{ is_state('device_tracker.ext_dome_01', 'home') }}"
    ext_dome_02:
      device_class: door
      entity_id: device_tracker.ext_dome_02
      friendly_name: Ext Dome 02 Connected
      value_template: "{{ is_state('device_tracker.ext_dome_02', 'home') }}"
