# Blue Iris is configured to send an alert to the MQTT topic for each camera when there is
# motion detected on camera. This works really well. 
- platform: mqtt
  name: "INT01 Motion"
  state_topic: blue_iris/binary_sensor/int01_motion/state
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
- platform: mqtt
  name: "INT02 Motion"
  state_topic: blue_iris/binary_sensor/int02_motion/state
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
- platform: mqtt
  name: "EXT01 Motion"
  state_topic: blue_iris/binary_sensor/ext01_motion/state
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
- platform: mqtt
  name: "EXT02 Motion"
  state_topic: blue_iris/binary_sensor/ext02_motion/state
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
- platform: mqtt
  name: "EXT03 Motion"
  state_topic: blue_iris/binary_sensor/ext03_motion/state
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
