- platform: template
  sensors:
    home_occupied:
      entity_id:
        - device_tracker.kamspixel
        - device_tracker.nickspixel
        - device_tracker.kameries_pixel
        - device_tracker.nickspixel_wifi
        - device_tracker.billies_phone
      value_template: >-
        {{ is_state('device_tracker.kamspixel', 'home')
           or is_state('device_tracker.nickspixel', 'home')
           or is_state('device_tracker.kameries_pixel', 'home')
           or is_state('device_tracker.nickspixel_wifi', 'home')
           or is_state('device_tracker.billies_phone', 'home') }}