# Getting the humidity from the Xiaomi sensors via zigbee2mqtt
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "averys_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "master_bedroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "guest_bathroom_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "guest_room_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "kitchen_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "laundry_room_humidity"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
  - "battery"
  - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "network_rack_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
  - "battery"
  - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "kams_desk_humidity"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
  - "battery"
  - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_southwall"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  name: "recroom_humidity_southwall"
  icon: "mdi:water-percent"
  value_template: "{{ value_json.humidity }}"
  json_attributes:
    - "battery"
    - "voltage"
