# Aqara Zibgee Motion Sensor
- platform: mqtt
  state_topic: "zigbee2mqtt/motion_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "recroom_northdoorway"
  class: motion
  value_template: "{{ value_json.illuminance }}"
  json_attributes:
  - "occupancy"
  - "battery"
  - "voltage"