# I use Xiaomi temp/humidity sensors and they report the temperature in Celcius.
# To get the temperature into Fahrenheit, I use a value_template.
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "averys_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "master_bedroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_bathroom_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "guest_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "kitchen_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
    - "battery"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "laundry_room_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
  - "battery"
  - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "network_rack_temperature"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
  json_attributes:
  - "battery"
  - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_southwall"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°F"
  name: "recroom_temperature_southwall"
  icon: "mdi:thermometer"
  value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
json_attributes:
  - "battery"
  - "voltage"
platform: "mqtt"
state_topic: "zigbee2mqtt/kams_desk"
availability_topic: "zigbee2mqtt/bridge/state"
unit_of_measurement: "°F"
name: "kams_desk_temperature"
icon: "mdi:thermometer"
value_template: "{{ ((float(value_json.temperature) * 9 / 5 )  +  32) | round(1) }}"
json_attributes:
- "battery"
- "voltage"
