# Create Sensors from the MQTT Stream Once. Then template them into values

# Temperature and Humidity Sensors
- platform: "mqtt"
  state_topic: "zigbee2mqtt/averys_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "averys_room_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/master_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "master_bedroom_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_bathroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "guest_bathroom_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/guest_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "guest_room_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "kitchen_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/laundry_room"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "laundry_room_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/network_rack"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "network_rack_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/recroom_southwall"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "recroom_southwall_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"
- platform: "mqtt"
  state_topic: "zigbee2mqtt/kams_desk"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "kams_desk_WSDCGQ01LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
    - "temperature"
    - "humidity"
    - "voltage"

## Occupancy and Luminance Sensors
- platform: mqtt
  state_topic: "zigbee2mqtt/motion_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  name: "recroom_northdoorway_RTCGQ11LM"
  value_template: "{{ value_json.battery }}"
  json_attributes:
  - "occupancy"
  - "illuminance"
  - "voltage"