- platform: generic
  still_image_url: 'http://grafana:3000/render/d-solo/MTH6SJxmz/edgewood?orgId=1&panelId=12&width=500&height=500&tz=America%2FIndianapolis'
  username: !secret grafana_user
  password: !secret grafana_password
  name: Indoor vs Outdoor Temperatures
- platform: generic
  still_image_url: 'http://grafana:3000/render/d-solo/kRYCDJxmz/docker?orgId=1&panelId=9&width=1000&height=500&tz=America%2FIndianapolis'
  username: !secret grafana_user
  password: !secret grafana_password
  name: Docker Container Memory Usage
- platform: generic
  still_image_url: 'http://grafana:3000/render/d-solo/kRYCDJxmz/docker?orgId=1&panelId=4&width=500&height=500&tz=America%2FIndianapolis'
  username: !secret grafana_user
  password: !secret grafana_password
  name: Docker Host Memory Usage